version: '3.8'

services:
  stock_trading_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    volumes:
      - .:/app
    restart: always
